import type { RawHardwareData } from './raw-hardware-data';

export interface Esp32HardwareInput {
  /**
   * Unique hardware identifier from ESP32 device.
   */
  deviceId: string;

  /**
   * Firmware version currently running on ESP32.
   */
  firmwareVersion: string;

  /**
   * Monotonic packet sequence number generated by ESP32.
   */
  sequence: number;

  /**
   * UTC timestamp generated by firmware when payload is sent.
   */
  sentAtUtc: string;

  /**
   * Physical transport from ESP32 to backend gateway.
   */
  transport: 'serial' | 'wifi';

  /**
   * 5 DOF joint angles in hardware envelope (degrees 0..180).
   */
  payload: RawHardwareData;

  /**
   * Optional CRC16 checksum in hex (4 chars) for frame integrity.
   */
  checksumCrc16?: string;
}
